version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      # Build the project
      - mvn package
      # create and upload a deployment package
      - sam package --template-file template.yml --s3-bucket cca-cw-ems --output-template-file template-output.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/EmployeeManagement-1.0.jar